name: Publish images to Docker Hub

on:
  push:
    branches: [ develop, tnet, main ]
    paths-ignore:
      - '.github/**'
  workflow_dispatch: # manually triggered
    inputs:
      environment:
        description: 'Environment name (one of: dev, tnet, prod)'
        required: false
        default: ''

jobs:
  build_and_push:
    name: Build and push
    runs-on: ubuntu-latest
    steps:
      -
        name: Check out the repo
        uses: actions/checkout@v2
      -
        name: Set branch name
        run: echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
      -
        name: Set sha tag
        run: |
          SHA_TAG=$(git rev-parse --short=12 "${{ github.sha }}")
          echo "SHA_TAG=$SHA_TAG" >> $GITHUB_ENV
      -
        name: Set main branch tag
        if: ${{ env.BRANCH == 'main' }}
        run: |
          echo "ENV_TAG=prod" >> $GITHUB_ENV
      -
        name: Set rc branch tag
        if: ${{ env.BRANCH == 'tnet' }}
        run: |
          echo "ENV_TAG=tnet" >> $GITHUB_ENV
      -
        name: Set develop branch tag
        if: ${{ env.BRANCH == 'develop' || env.ENV_TAG == '' }}
        run: |
          echo "ENV_TAG=dev" >> $GITHUB_ENV
      -
        name: Set environment from manual input
        if: ${{ github.event.inputs.environment != '' }}
        run: |
          echo "ENV_TAG=${{ github.event.inputs.environment }}" >> $GITHUB_ENV
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push image
        env:
          IMAGE_ID: "3boxlabs/ipfs-pinset-migration"
        run: |
          EXTRA_TAGS=""
          if [[ "${{ env.ENV_TAG }}" == "prod" ]]; then
            EXTRA_TAGS="--tag $IMAGE_ID:latest"
          fi
          docker buildx build . --output 'type=image,push=true' \
            --tag $IMAGE_ID:${{ env.ENV_TAG }} \
            --tag $IMAGE_ID:${{ env.SHA_TAG }} \
            --tag $IMAGE_ID:${{ github.sha }}  \
            $EXTRA_TAGS
